/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CardDialog: typeof import('./components/CardDialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Kanban: typeof import('./components/Kanban.vue')['default']
    KanbanCard: typeof import('./components/KanbanCard.vue')['default']
    KanbanSection: typeof import('./components/KanbanSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
